name: Deploy React to Render

on:
  push:
    branches: ["main", "dev"]

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          # checkout
          - name: checkout
            uses: actions/checkout@v7

            # Installera node
          - name: Set up Node
            uses: actions/setup-node@v7
            with:
              node-version: '26'

          # npm install
          - name: install dependencies
            run: npm ci

            # build -> ./dist
          - name: build
            run: npm run build

            # upload ./dist

